from(bucket: "my-bucket")
    |> range(start: -1d)
    |> filter(fn: (r) => r["_measurement"] == "bench")
    |> group(columns: ["_field"])
    |> aggregateWindow(every: 15m, fn: mean, createEmpty: false)
    |> yield(name: "mean")
